# distinct terms in the sequence generated by a^b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100


powers = []

for a in range(2, 101):
	for b in range(2, 101):
		powers.append(a ** b)

powers.sort()
print(len(set(powers)))
